bruh: ENC[AES256_GCM,data:EZYIn81n,iv:otC8L9FNxIa5wd40VVk5UZ9chTfAMQyz4QBkemZDlt4=,tag:6LoX9eQcIMwZrGFH4kTd7g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dkjx86qcusr6pu3rxxy4ju053h3fl6t7lqvjwnlfrdlhn2nzpcjqffer7j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTkJ4cytYcmVqNFllOXZD
            ZGUzRnB2VTJTSkFWR24zUVhvUCtLWWNjTzM0CkxSMmhBcVdUeWU2WWVrQmhWc2VM
            ZEd2Um83cFJBMUlmUHEybHhIMGgraHMKLS0tIEFqcmoxdjVwWHYyak9DSldXRjZr
            N042TGJCNHhwRUhqOXhuN3BoTHdLWXcKx/di5Astn4r5poj+LvdS0XSaKTbLcLBS
            88v8SFWlFkY2GkX1j/O8AEb+JhsNvOeJga77OEZszoVuB+xICOd+qg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-22T19:55:15Z"
    mac: ENC[AES256_GCM,data:u/cOBGd20twhJEMvLuhWgjqHgyjMCSvj6C1wwtwgQTNZoG5s7lRRZoYT9V+1PzZ48Ykn35eEEZeUgdWeYu3P9KFMcFZT3o0L9GNgauYGm6TM2Vx+cQLJqC1ThpSjuw5Q/LX3O8faVmB21UOXrPjtjn11T96s6Nc14Oqt69br4+U=,iv:weZqrbe+nCWYH0oyfKZb87DuyYVK4xbq+CZCJ5KAX9M=,tag:+V8GyICCi5AFZclv2dBNSw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.3
